[build]
  command = "yarn build --configuration=production"
  publish = "dist/portfolio/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
